# Architecture
#TARGET_ARCH := arm64
#TARGET_ARCH_VARIANT := armv8-a
#TARGET_CPU_ABI := arm64-v8a
#TARGET_CPU_ABI2 :=
#TARGET_CPU_VARIANT := cortex-a53
#TARGET_CPU_CORTEX_A53 := true

#TARGET_IS_64_BIT := true
#TARGET_BOARD_SUFFIX := _64
#TARGET_USES_64_BIT_BINDER := true
#MTK_K64_SUPPORT := yes

#TARGET_2ND_ARCH := arm
#TARGET_2ND_ARCH_VARIANT := armv7-a-neon
#TARGET_2ND_CPU_ABI := armeabi-v7a
#TARGET_2ND_CPU_ABI2 := armeabi
#TARGET_2ND_CPU_VARIANT := cortex-a53

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_CORTEX_A53 := true

#Architecture Extensions
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_VFP := true
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_TLS_REGISTER := true

# Platform
TARGET_BOARD_PLATFORM := mt6753
TARGET_BOOTLOADER_BOARD_NAME := mt6735
TARGET_NO_BOOTLOADER := true
TARGET_GLOBAL_CFLAGS   += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

# Kernel
BOARD_NAME := 1505900635
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,32N2
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_TAGS_OFFSET := 0x0e000000
BOARD_SECOND_OFFSET := 0x00f00000


BOARD_MKBOOTIMG_ARGS :=  --base $(BOARD_KERNEL_BASE) --pagesize $(BOARD_KERNEL_PAGESIZE) --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET) --second_offset $(BOARD_SECOND_OFFSET) --board $(BOARD_NAME)

TARGET_PREBUILT_KERNEL :=  device/Oukitel/K10000_Max/kernel
#TARGET_PREBUILT_RECOVERY_KERNEL := $(DEVICE_FOLDER)/kernel

TARGET_RECOVERY_DEVICE_DIRS := device/Oukitel/K10000_Max
TARGET_RECOVERY_INITRC := device/Oukitel/K10000_Max/recovery/root/init.rc
TARGET_RECOVERY_FSTAB := device/Oukitel/K10000_Max/recovery/root/etc/recovery.fstab

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2625634304
BOARD_CACHEIMAGE_PARTITION_SIZE := 419430400
BOARD_USERDATAIMAGE_PARTITION_SIZE := 28021620736


# Partitions types
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true

BOARD_HAS_REMOVABLE_STORAGE := true

# USB Mounting
#TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/musb-hdrc.0.auto/gadget/lun%d/file
#TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/virtual/android_usb/android0/f_mass_storage/lun/file

#fix Wipe
BOARD_SUPPRESS_EMMC_WIPE := true

# Recovery
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"

#Display

#USE_OPENGL_RENDERER := true
TARGET_SCREEN_HEIGHT := 1920
TARGET_SCREEN_WIDTH := 1080


BOARD_USE_FRAMEBUFFER_ALPHA_CHANNEL := true
TARGET_DISABLE_TRIPLE_BUFFERING := false
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
RECOVERY_GRAPHICS_USE_LINELENGTH := true

RECOVERY_SDCARD_ON_DATA := true

# TWRP
DEVICE_RESOLUTION := 1080x1920
DEVICE_SCREEN_WIDTH := 1080
DEVICE_SCREEN_HEIGHT := 1920

TW_THEME := portrait_hdpi
TWRP_NEW_THEME := true
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 75
TW_DEFAULT_LANGUAGE := ru
TW_DEFAULT_EXTERNAL_STORAGE := true
#TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
#TW_CUSTOM_BATTERY_PATH := /sys/devices/platform/battery/power_supply/battery
#TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
TW_INTERNAL_STORAGE_PATH := "/data/media"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"
#TW_SCREEN_BLANK_ON_BOOT := true
TW_REBOOT_BOOTLOADER := true
TW_FLASH_FROM_STORAGE := true
TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_NTFS_3G := true
TW_NO_EXFAT_FUSE := true

#TWHAVE_SELINUX := true

#TWRP_EVENT_LOGGING := true
#TW_INPUT_BLACKLIST := "hbtp_vm"
#BOARD_HAS_NO_SELECT_BUTTON := true
#BOARD_HAS_NO_REAL_SDCARD := # 
#TW_DEFAULT_EXTERNAL_STORAGE := true
#TW_NO_USB_STORAGE := true
